---
- hosts: dev
  become: True
  tasks:
    - name: start the container
      docker_container:
        name: image
        image: "bachnguyen18/image:{{DOCKER_TAG}}"
        state: started
        ports:
          - "8080:80"
