---
- hosts: dev
  become: True
  tasks:

    - name: pull docker image from dockerhub
      command: docker pull bachnguyen18/image:latest

    - name: creating docker container using image
      command: docker run -d --name container -p 8080:8080 bachnguyen18/image:latest

